# Generated by Django 3.1 on 2020-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuesday', '0002_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='email',
            field=models.CharField(max_length=70),
        ),
    ]
